image: gitlab/gitlab-runner:alpine-v11.5.0
imagePullPolicy: IfNotPresent
init:
  image: busybox
  tag: latest
gitlabUrl: <gitlab-url>
runnerRegistrationToken: "<registration-token>"
unregisterRunners: true
concurrent: 2
checkInterval: 30
rbac:
  create: false
metrics:
  enabled: false
runners:
  image: ubuntu:16.04
  privileged: true
  cache: {}
  builds: {}
  services: {}
  helpers: {}
resources: {}
