apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysql-apiserver
  namespace: staging
spec:
  host: mysql-apiserver
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mysql-apiserver
  namespace: staging
spec:
  hosts:
  - mysql-apiserver
  http:
  - fault:
      delay:
        fixedDelay: 5s
        percent: 100
    route:
    - destination:
        host: mysql-apiserver
        subset: v1
  - route:
    - destination:
        host: mysql-apiserver
        subset: v1