apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: projbackend
  labels:
    app: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/smiyoshi/sectest-database:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: jkd201812
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: projbackend
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
