apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: projfrontend
  labels:
    app: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/smiyoshi/sectest-frontend:latest
        ports:
          - containerPort: 4567
        env:
        - name: API_SERVER_URL
          value: mysql-apiserver.projbackend.svc.cluster.local
      imagePullSecrets:
      - name: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: projfrontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 4567
    targetPort: 4567
    nodePort: 30010
  selector:
    app: frontend
